### ISSUE TITLE
build error :: nasmjf.asm:665: error: comma expected after operand 1

### ISSUE THREAD

**Issue by brwlo** [ratfactor/nasmjf#1]
running ./build i gets me the message "nasmjf.asm:665: error: comma expected after operand 1".

if i the add another comma after operand 1 it asks for another after operand 2 and if i add the second comma, nasm complains that the symbol "dup" hasn't been defined yet.

**Comment by ratfactor** [comment]
@brwlo I just ran into that too! This is bizarre. It's hard to imagine something so fundamental changed in NASM since I did my last commit...and yet I'm pretty sure I left this in a good state at that point. :thinking:

**Comment by brwlo** [comment]
oh! i figured it out with the help of this link [https://stackoverflow.com/questions/64235907/comma-expected-after-operand-1-when-defining-a-series-of-bytes-in-nasm](https://stackoverflow.com/questions/64235907/comma-expected-after-operand-1-when-defining-a-series-of-bytes-in-nasm): the "dup" syntax is not present in versions of nasm  lesser then 2.15, mine being 2.13.

changing it from `db 32 dup (0)` to `times db 32 0x0` fixes this problem, leaving me to investigate the next issue ("nasmjf.o not compatible with i386:x86-64").

(this next issue, by the way, was solved by changing `ld $F.o -o $F` to `ld -m elf_i386 $F.o -s -o $F` in the build script.)

**Comment by ratfactor** [comment]
Oh! Right, I developed this on a 32-bit CPU! Ha ha.

**Comment by ratfactor** [comment]
@brwlo Your fixes look universal to me. Most people will probably try this on 64bit machines. Would you mind sending a PR?

**Comment by brwlo** [comment]
it's done.
